### PR TITLE
Feature/test-suit

### PR DESCRIPTION
**Pull request by george-shammar**
This pull request seeks to merge the features of the feature/test-suit branch to the development branch. The features to be merged include test examples for the following enumerable methods:
1. my_each
2. my_each-with_index
3. my_select
4. my_all?
5. my_any?
6. my_none?
7. my_count
8. my_map
9. my_inject.

### CODE REVIEW

**Review by blackpintz — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑

## Hello team 👋,

**You have done an excellent job in this project 👏. However, there are a few requirements needed.**

1). **Ensure the linter checks are showing for your pull request.**
2). **There are a few rubocop offenses that are not auto-correctable with `rubocop -a`. See screenshot below.**
rubocop

3). **Use `let` for data that is repeated across several examples. [Here](https://github.com/rubocop-hq/rspec-style-guide#let-blocks) is a reference to how you can use it. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/before_each.png) from pathwright.**


### Happy coding 🥂.

**PS: You can reach me on slack (Rose Wanjohi).**

**Comment by jpdf00** [comment]
Hi.
About this requirement. "1). Please move the tests to the original repository where you created your enumerable methods. See screenshot from pathwright about this requirement."

This repository was forked because I did the enumerables project with a different partner. What if she had decided to do this project in her repo? So in order to avoid conflicts between us, We forked the repo, so for all purposes, this is the repo I did the enumerables with my previous partner.

For example, the partner I did the Tic-Tac-Toe with is doing this project on his repo and I am doing it on a fork from that repo in order to avoid any conflicts between our Rspec projects. By the way, my Rspec for the Tic-Tac-Toe was reviewed and the TSE didn't complain about that.

**Comment by jpdf00** [comment]
We used `let` to create variables for most o the methods we tested, but for `#my_all?`, `#my_any?`, and `#my_none?` we saw that it was inefficient to declare variables due to most test cases having small variations to ensure that the tests cover all possible cases.
For example, we have arrays that look similar like `%w[ant bear cat]`, `%w[ant bat cat]`, `%w[ant bear bat]`, `%w[cat cat cat]` but are tailored for each case and creating a variable for each seemed very inefficient.

**Review by LamiaSristy — APPROVED** [review]
# Status: Approved. 💯 🥇 

Well done Team!! 👏 👏 👏 👏 

Your project is now approved. Congratulations on your hard work. 🛠️ 


You can merge the branch now, good luck with your next project 🚀.

Feel free to reach me at @lamiasristy 🙋

**Pull request merged**
